# 공통

#springboot admin 설정
boot:
  admin:
    client:
      url: http://localhost:8000
    instance:
      name: quing
mvc:
  pathmatch:
    matching-strategy: ant_path_matcher

#spring actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#springdoc swagger
springdoc:
  api-docs:
    path: /docs

  swagger-ui:
    path: /swagger-ui
    display-request-duration: true  # try it out 을 했을 때 request duration 을 추가로 찍어줌

  cache:
    disabled: true # swagger cache 설정

#spring-session-jdbc
spring:
  session:
    store-type: jdbc
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
---
spring:
  config:
    activate:
      on-profile: dev
    import:
    - classpath:mysql-conn.yml # datasource: driver, url, username, password
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 80
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:mysql-conn.yml # datasource: driver, url, username, password
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 80