spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/dbname?serverTimezone=Asia/Seoul
    username: ##
    password: ##
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/dbname?serverTimezone=Asia/Seoul
    username: ##
    password: ##
  jpa:
    hibernate:
      ddl-auto: none